### PR TITLE
display more helpful error message on broken keychain

### LINKED ISSUE #144: broken keychain results in not helpful error
First of all thanks for this great tool 👍,

If keychain is broken for any reason, an not helpful error will be displayed to the user.
As I found out the easiest way to fix this, is to remove the broken keychains and to try it again.

It would be great for the user to show some more helpful error message.
I will add an PR soon.

### PR DESCRIPTION
**Pull request by smollweide**
fixes #144

### CODE REVIEW

**Comment by gr2m** [comment]
Thanks for the pull request @smollweide and welcome to semantic-release :) 

I've changed your pull request description from "PR for #144" to "closes #144", that way the issue will get closed automatically when we merge your pull request. I'll have a look at your changes now

**Comment by gr2m** [comment]
What error did you get exactly?

Also note that the keychains are implemented differently on Windows, Mac and Linux, I'm not sure if the all have the same keys (e.g. "semantic-release-cli:npm").

I would also still log the actual error in case it's something different than what we anticipate.

**Comment by smollweide** [comment]
If I run "semantic-release-cli setup" after step "What is your npm username" the following massage is displayed:
```
ERR! semantic-release Error: The user name or passphrase you entered is not correct.
ERR! semantic-release     at Error (native)
```

with my fix the error message will be:
```
ERR! semantic-release It seems something went wrong with your credentials stored in your keychain.
ERR! semantic-release At it's best you delete the "semantic-release" keychains and retry it.
ERR! semantic-release The keychain names are "semantic-release-cli:npm" and "semantic-release-cli:github"
ERR! semantic-release Error: The user name or passphrase you entered is not correct.
ERR! semantic-release     at Error (native)
```

It seems this happens in case of the node hasn't read rights on the keychain. The origin error is executed by the dependency "keytar".

**Comment by gr2m** [comment]
I would suggest we shorten the error message a bit, how about:

> Something went wrong with your stored credentials. Delete them from your keychain and try again

If you could also rebase your pull request on the latest master, that would be great. But don't worry, I can do that for you or help you out if you have any questions or trouble doing it yourself :)

**Comment by smollweide** [comment]
I did something wrong with the rebase

**Pull request closed without merging**
