### PR TITLE
feat: Remember passwords

### LINKED ISSUE #13: Remember password
It would be nice if the cli would remember my passwords. I recently used https://github.com/atom/node-keytar for this and was happy with it.

### PR DESCRIPTION
**Pull request by jo**
Store npm and github passwords in the keychain. Can be disabled via
`--no-keychain` flag.

Closes #13

### CODE REVIEW

**Comment by boennemann** [comment]
I'm so excited for this one, thank you so much @jo.

I have a few nitpicks left though (sorry).

1. Please start the commit message with a lower case
2. [Travis shows that gnome-keyring couldn't be installed](https://travis-ci.org/semantic-release/cli/jobs/76159376#L84) as the tests are still passing I'm assuming we can just leave it out entirely then
3. The indentation in .travis.yml doesn't seem right [1](https://github.com/eHealthAfrica/cli/blob/ff7aacedf4efb9185fdd05fb1c17060ac60ba0d5/.travis.yml#L11-L13) [2](https://github.com/eHealthAfrica/cli/blob/ff7aacedf4efb9185fdd05fb1c17060ac60ba0d5/.travis.yml#L20-L27) You can remove one level.
4. I just tried this locally and pasted the wrong GitHub password. On second try the password was already cached and I had to use the `--no-keychain` flag. It would be nice the storing would only happen after the respective APIs didn't return an error, so we're only storing correct credentials.

Let me know if you want to fix this, I can do it as well :)

Best,
Stephan

**Comment by jo** [comment]
Sure, I'm happy to do this :)

**Comment by jo** [comment]
good points btw. :+1:

**Comment by jo** [comment]
done :rocket:

**Comment by boennemann** [comment]
Tried it again locally and it's fantastic :+1: 

One thing I noticed is that it's still writing to the keychain, even with `--no-keychain'. I'm not 100% sure how I would want that to behave, but that may be confusing. Might also just be the naming of the flag.
Really undecided on how to proceed now ¯\_(ツ)_/¯ Any ideas?

**Comment by jo** [comment]
I also think this is confusing.

Maybe we can always remove the passwords from the keychain when ‘--no-keychain‘ is used. But that's also confusing because it changes the state and previously entered passwords were lost.

Or we go with my initial approach using inquirer's ‘default‘.

The third possible solution which comes to my mind is introducing a second flag, ‘--wipe-keychain‘

**Comment by boennemann** [comment]
Okay I think this would be a good way forward:

1. Don't store to the keychain w/ --no-keychain
2. Add a `--wipe-keychain` flag, which deletes every entry added by the CLI before running the actual command

**Comment by jo** [comment]
Just had the idea that we could simply wipe the password everytime authentication fails. We can still go with `--wipe-keychain` flag.

**Comment by boennemann** [comment]
Authentication could fail because of having no internet, or the service being down. If we could nail it down to the specific error type I'm up for it. But I think we can add the --wipe-keychain now, and get the feature out first :)

**Comment by jo** [comment]
d'accord!

**Comment by jo** [comment]
It turns out that with node-keytar you can only whipe passwords for accounts you know, rendering the semantic of the global implicating `--wipe-keychain` switch senseless.

We can name it `--reset-passwords` or `--ask-for-passwords` or so, it would then just ask for the passwords and store the new one. What do you think?

**Comment by jo** [comment]
Or call the flag just `--passwords`

**Comment by boennemann** [comment]
`--ask-for-passwords` shortcutted to `--ask` sounds good, imho :)

**Comment by boennemann** [comment]
Hell Yeah!

**Pull request merged**
